import type { AccountTemplate } from "./types";

/** Generic US GAAP-style chart of accounts (used for US, CA, GB, AU, NZ, etc.) */
export const GENERIC_ACCOUNTS: AccountTemplate[] = [
  // Assets (1xxx)
  { code: "1000", name: "Cash", type: "asset", subType: "current" },
  { code: "1010", name: "Petty Cash", type: "asset", subType: "current" },
  { code: "1100", name: "Checking Account", type: "asset", subType: "bank" },
  { code: "1110", name: "Savings Account", type: "asset", subType: "bank" },
  { code: "1200", name: "Accounts Receivable", type: "asset", subType: "current" },
  { code: "1300", name: "Inventory", type: "asset", subType: "current" },
  { code: "1310", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "1400", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "1410", name: "Prepaid Insurance", type: "asset", subType: "current" },
  { code: "1500", name: "Input Tax Credits", type: "asset", subType: "current" },
  { code: "1600", name: "Equipment", type: "asset", subType: "fixed" },
  { code: "1610", name: "Furniture & Fixtures", type: "asset", subType: "fixed" },
  { code: "1620", name: "Computer Equipment", type: "asset", subType: "fixed" },
  { code: "1630", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "1640", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "1650", name: "Land", type: "asset", subType: "fixed" },
  { code: "1700", name: "Accumulated Depreciation - Equipment", type: "asset", subType: "fixed" },
  { code: "1710", name: "Accumulated Depreciation - Furniture", type: "asset", subType: "fixed" },
  { code: "1720", name: "Accumulated Depreciation - Computers", type: "asset", subType: "fixed" },
  { code: "1730", name: "Accumulated Depreciation - Vehicles", type: "asset", subType: "fixed" },
  // Liabilities (2xxx)
  { code: "2000", name: "Accounts Payable", type: "liability", subType: "current" },
  { code: "2100", name: "Accounts Payable - Trade", type: "liability", subType: "current" },
  { code: "2200", name: "Tax Payable", type: "liability", subType: "current" },
  { code: "2210", name: "GST/VAT Payable", type: "liability", subType: "current" },
  { code: "2220", name: "Income Tax Payable", type: "liability", subType: "current" },
  { code: "2300", name: "Accrued Expenses", type: "liability", subType: "current" },
  { code: "2310", name: "Wages Payable", type: "liability", subType: "current" },
  { code: "2400", name: "Unearned Revenue", type: "liability", subType: "current" },
  { code: "2500", name: "Short-Term Loans", type: "liability", subType: "current" },
  { code: "2600", name: "Credit Card Payable", type: "liability", subType: "current" },
  { code: "2700", name: "Long-Term Debt", type: "liability", subType: "non_current" },
  { code: "2800", name: "Mortgage Payable", type: "liability", subType: "non_current" },
  // Equity (3xxx)
  { code: "3000", name: "Owner's Equity", type: "equity", subType: "equity" },
  { code: "3100", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "3200", name: "Owner's Drawings", type: "equity", subType: "equity" },
  { code: "3300", name: "Common Stock", type: "equity", subType: "equity" },
  // Revenue (4xxx)
  { code: "4000", name: "Sales Revenue", type: "revenue", subType: "operating" },
  { code: "4010", name: "Service Revenue", type: "revenue", subType: "operating" },
  { code: "4020", name: "Consulting Revenue", type: "revenue", subType: "operating" },
  { code: "4100", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "4200", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "4300", name: "Gain on Asset Disposal", type: "revenue", subType: "non_operating" },
  { code: "4900", name: "Other Revenue", type: "revenue", subType: "non_operating" },
  // Expenses (5xxx)
  { code: "5000", name: "Cost of Goods Sold", type: "expense", subType: "cogs" },
  { code: "5100", name: "Wages & Salaries", type: "expense", subType: "operating" },
  { code: "5110", name: "Employee Benefits", type: "expense", subType: "operating" },
  { code: "5120", name: "Payroll Tax", type: "expense", subType: "operating" },
  { code: "5200", name: "Rent Expense", type: "expense", subType: "operating" },
  { code: "5210", name: "Utilities", type: "expense", subType: "operating" },
  { code: "5220", name: "Internet & Phone", type: "expense", subType: "operating" },
  { code: "5300", name: "Office Supplies", type: "expense", subType: "operating" },
  { code: "5310", name: "Postage & Shipping", type: "expense", subType: "operating" },
  { code: "5400", name: "Insurance", type: "expense", subType: "operating" },
  { code: "5500", name: "Depreciation Expense", type: "expense", subType: "operating" },
  { code: "5600", name: "Marketing & Advertising", type: "expense", subType: "operating" },
  { code: "5700", name: "Professional Fees", type: "expense", subType: "operating" },
  { code: "5710", name: "Legal Fees", type: "expense", subType: "operating" },
  { code: "5720", name: "Accounting Fees", type: "expense", subType: "operating" },
  { code: "5800", name: "Travel Expense", type: "expense", subType: "operating" },
  { code: "5810", name: "Meals & Entertainment", type: "expense", subType: "operating" },
  { code: "5900", name: "Bank Fees & Charges", type: "expense", subType: "operating" },
  { code: "5910", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "5920", name: "Loss on Asset Disposal", type: "expense", subType: "non_operating" },
  { code: "5990", name: "Miscellaneous Expense", type: "expense", subType: "operating" },
];
