// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api-reference/index.mdx": () => import("../content/docs/api-reference/index.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "guides/api-integration.mdx": () => import("../content/docs/guides/api-integration.mdx?collection=docs"), "guides/index.mdx": () => import("../content/docs/guides/index.mdx?collection=docs"), "guides/multi-currency.mdx": () => import("../content/docs/guides/multi-currency.mdx?collection=docs"), "modules/banking.mdx": () => import("../content/docs/modules/banking.mdx?collection=docs"), "modules/bills.mdx": () => import("../content/docs/modules/bills.mdx?collection=docs"), "modules/budgets.mdx": () => import("../content/docs/modules/budgets.mdx?collection=docs"), "modules/chart-of-accounts.mdx": () => import("../content/docs/modules/chart-of-accounts.mdx?collection=docs"), "modules/contacts.mdx": () => import("../content/docs/modules/contacts.mdx?collection=docs"), "modules/expenses.mdx": () => import("../content/docs/modules/expenses.mdx?collection=docs"), "modules/fixed-assets.mdx": () => import("../content/docs/modules/fixed-assets.mdx?collection=docs"), "modules/index.mdx": () => import("../content/docs/modules/index.mdx?collection=docs"), "modules/inventory.mdx": () => import("../content/docs/modules/inventory.mdx?collection=docs"), "modules/invoicing.mdx": () => import("../content/docs/modules/invoicing.mdx?collection=docs"), "modules/journal-entries.mdx": () => import("../content/docs/modules/journal-entries.mdx?collection=docs"), "modules/payroll.mdx": () => import("../content/docs/modules/payroll.mdx?collection=docs"), "modules/projects.mdx": () => import("../content/docs/modules/projects.mdx?collection=docs"), "modules/reports.mdx": () => import("../content/docs/modules/reports.mdx?collection=docs"), "modules/tax-rates.mdx": () => import("../content/docs/modules/tax-rates.mdx?collection=docs"), "self-hosting/index.mdx": () => import("../content/docs/self-hosting/index.mdx?collection=docs"), }),
};
export default browserCollections;