import {
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";
import { EmailLayout } from "./layout";

interface StatementTransaction {
  date: string;
  type: string;
  documentNumber: string;
  description: string;
  debit: string;
  credit: string;
  balance: string;
}

interface StatementEmailProps {
  contactName: string;
  organizationName: string;
  startDate: string;
  endDate: string;
  openingBalance: string;
  closingBalance: string;
  totalDebit: string;
  totalCredit: string;
  transactions: StatementTransaction[];
}

export function StatementEmail({
  contactName = "John Doe",
  organizationName = "Acme Corp",
  startDate = "Jan 1, 2026",
  endDate = "Mar 12, 2026",
  openingBalance = "$0.00",
  closingBalance = "$1,250.00",
  totalDebit = "$2,500.00",
  totalCredit = "$1,250.00",
  transactions = [],
}: StatementEmailProps) {
  return (
    <EmailLayout preview={`Statement from ${organizationName} - ${startDate} to ${endDate}`}>
      <Section style={content}>
        <Text style={heading}>Statement</Text>
        <Text style={subheading}>{organizationName}</Text>

        <Section style={metaRow}>
          <Text style={metaLeft}>{contactName}</Text>
          <Text style={metaRight}>{startDate} to {endDate}</Text>
        </Section>

        {/* Summary cards */}
        <Section style={summaryRow}>
          <table style={summaryTable} cellPadding={0} cellSpacing={0}>
            <tbody>
              <tr>
                <td style={summaryCell}>
                  <Text style={summaryLabel}>Opening</Text>
                  <Text style={summaryValue}>{openingBalance}</Text>
                </td>
                <td style={summaryCell}>
                  <Text style={summaryLabel}>Debited</Text>
                  <Text style={summaryValue}>{totalDebit}</Text>
                </td>
                <td style={summaryCell}>
                  <Text style={summaryLabel}>Credited</Text>
                  <Text style={summaryValue}>{totalCredit}</Text>
                </td>
                <td style={summaryCell}>
                  <Text style={summaryLabel}>Closing</Text>
                  <Text style={summaryValue}>{closingBalance}</Text>
                </td>
              </tr>
            </tbody>
          </table>
        </Section>

        {/* Transactions table */}
        {transactions.length > 0 && (
          <table style={txTable} cellPadding={0} cellSpacing={0}>
            <thead>
              <tr>
                <th style={txTh}>Date</th>
                <th style={txTh}>Type</th>
                <th style={txTh}>Ref</th>
                <th style={{ ...txTh, textAlign: "right" }}>Debit</th>
                <th style={{ ...txTh, textAlign: "right" }}>Credit</th>
                <th style={{ ...txTh, textAlign: "right" }}>Balance</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colSpan={5} style={txTdBold}>Opening Balance</td>
                <td style={{ ...txTdBold, textAlign: "right", fontFamily: "monospace" }}>{openingBalance}</td>
              </tr>
              {transactions.map((tx, i) => (
                <tr key={i}>
                  <td style={txTd}>{tx.date}</td>
                  <td style={txTd}>{tx.type}</td>
                  <td style={txTd}>{tx.documentNumber}</td>
                  <td style={{ ...txTd, textAlign: "right", fontFamily: "monospace" }}>{tx.debit || "-"}</td>
                  <td style={{ ...txTd, textAlign: "right", fontFamily: "monospace" }}>{tx.credit || "-"}</td>
                  <td style={{ ...txTd, textAlign: "right", fontFamily: "monospace" }}>{tx.balance}</td>
                </tr>
              ))}
              <tr>
                <td colSpan={5} style={txTdBold}>Closing Balance</td>
                <td style={{ ...txTdBold, textAlign: "right", fontFamily: "monospace" }}>{closingBalance}</td>
              </tr>
            </tbody>
          </table>
        )}

        <Text style={footerNote}>
          This statement was generated by {organizationName}.
        </Text>
      </Section>
    </EmailLayout>
  );
}

export default StatementEmail;

const content: React.CSSProperties = { padding: "24px 32px" };
const heading: React.CSSProperties = { fontSize: "20px", fontWeight: 700, color: "#111", margin: "0 0 4px" };
const subheading: React.CSSProperties = { fontSize: "13px", color: "#666", margin: "0 0 24px" };

const metaRow: React.CSSProperties = { marginBottom: "16px" };
const metaLeft: React.CSSProperties = { fontSize: "14px", fontWeight: 600, color: "#111", margin: 0, display: "inline" };
const metaRight: React.CSSProperties = { fontSize: "12px", color: "#666", margin: 0, textAlign: "right" };

const summaryRow: React.CSSProperties = { margin: "0 0 24px" };
const summaryTable: React.CSSProperties = { width: "100%", backgroundColor: "#f6f9fc", borderRadius: "6px" };
const summaryCell: React.CSSProperties = { textAlign: "center", padding: "12px" };
const summaryLabel: React.CSSProperties = { fontSize: "10px", textTransform: "uppercase", color: "#888", margin: 0 };
const summaryValue: React.CSSProperties = { fontSize: "14px", fontWeight: 600, fontFamily: "monospace", color: "#111", margin: "4px 0 0" };

const txTable: React.CSSProperties = { width: "100%", borderCollapse: "collapse", marginBottom: "24px" };
const txTh: React.CSSProperties = { padding: "8px", textAlign: "left", fontSize: "10px", textTransform: "uppercase", color: "#888", fontWeight: 500, borderBottom: "1px solid #ddd", backgroundColor: "#f5f5f5" };
const txTd: React.CSSProperties = { padding: "6px 8px", borderBottom: "1px solid #eee", fontSize: "12px" };
const txTdBold: React.CSSProperties = { ...txTd, fontWeight: 600, backgroundColor: "#f9f9f9" };

const footerNote: React.CSSProperties = { fontSize: "11px", color: "#999", marginTop: "24px" };
