import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { AuthContext } from "@/lib/api/auth-context";
import { registerOrganizationTools } from "./organization";
import { registerAccountTools } from "./accounts";
import { registerEntryTools } from "./entries";
import { registerContactTools } from "./contacts";
import { registerInvoiceTools } from "./invoices";
import { registerBillTools } from "./bills";
import { registerReportTools } from "./reports";
import { registerNotificationTools } from "./notifications";
import { registerRoleTools } from "./roles";
import { registerTimeTrackingTools } from "./time-tracking";
import { registerWebhookTools } from "./webhooks";
import { registerReportScheduleTools } from "./report-schedule-tools";
import { registerApprovalTools } from "./approvals";
import { registerBankRuleTools } from "./bank-rules";
import { registerDocumentTools } from "./documents";
import { registerIntegrationTools } from "./integrations";
import { registerEmailTools } from "./email";
import { registerPeriodCloseTools } from "./period-close";

export function registerAllTools(server: McpServer, ctx: AuthContext) {
  registerOrganizationTools(server, ctx);
  registerAccountTools(server, ctx);
  registerEntryTools(server, ctx);
  registerContactTools(server, ctx);
  registerInvoiceTools(server, ctx);
  registerBillTools(server, ctx);
  registerReportTools(server, ctx);
  registerNotificationTools(server, ctx);
  registerRoleTools(server, ctx);
  registerTimeTrackingTools(server, ctx);
  registerWebhookTools(server, ctx);
  registerReportScheduleTools(server, ctx);
  registerApprovalTools(server, ctx);
  registerBankRuleTools(server, ctx);
  registerDocumentTools(server, ctx);
  registerIntegrationTools(server, ctx);
  registerEmailTools(server, ctx);
  registerPeriodCloseTools(server, ctx);
}
